{"name": "Проверяем, что если не передано поле логина или пароля, запрос возвращает ошибку 400", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код в ответе: ожидался 400, получен \"504\", ответ: \"Service unavailable\"", "trace": "self = <test_login_courier.TestLoginCourier object at 0x000002BE1174D490>\ncreate_new_courier = {'firstName': 'fcdmyaijol', 'login': 'sqkvpyggwm', 'password': 'zkpxjupbls'}, key = 'password'\n\n    @pytest.mark.parametrize('key', [KEYS.LOGIN, KEYS.PASSWORD])\n    @allure.title('Проверяем, что если не передано поле логина или пароля, запрос возвращает ошибку 400')\n    def test_login_courier_missing_field_error(self, create_new_courier, key):\n        # создаем нового курьера и получаем его данные\n        user_data = create_new_courier\n        # формируем данные для запроса без поля key\n        payload = user_data.copy()\n        payload.pop(key)\n        # отправляем запрос на регистрацию курьера и сохраняем ответ в переменную response\n        response = register_courier(payload)\n        # проверяем что получен код ответа 400\n>       check_status_code(response, code.BAD_REQUEST)\n\ntests\\test_login_courier.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [504]>, expected_code = 400\n\n    @allure.step('Проверяем код ответа')\n    def check_status_code(response, expected_code):\n        # проверяем что получен код ответа expected_code\n        received_code = response.status_code\n>       assert received_code == expected_code, f'Неверный код в ответе: ожидался {expected_code}, получен \"{received_code}\", ответ: \"{response.text}\"'\nE       AssertionError: Неверный код в ответе: ожидался 400, получен \"504\", ответ: \"Service unavailable\"\n\nhelpers\\helpers_on_check_response.py:12: AssertionError"}, "steps": [{"name": "Отправляем API-запрос на регистрацию нового курьера/получение id курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'sqkvpyggwm', 'firstName': 'fcdmyaijol'}"}], "start": 1701712239396, "stop": 1701712299441}, {"name": "Проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код в ответе: ожидался 400, получен \"504\", ответ: \"Service unavailable\"\n", "trace": "  File \"C:\\Python_projects\\Python_QA\\qa_python_1\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Python_projects\\Python_QA\\qa_python_7\\helpers\\helpers_on_check_response.py\", line 12, in check_status_code\n    assert received_code == expected_code, f'Неверный код в ответе: ожидался {expected_code}, получен \"{received_code}\", ответ: \"{response.text}\"'\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [504]>"}, {"name": "expected_code", "value": "400"}], "start": 1701712299441, "stop": 1701712299441}], "attachments": [{"name": "stdout", "source": "b3a21af8-0b54-487e-86e3-eb0da78dee63-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "key", "value": "'password'"}], "start": 1701712239396, "stop": 1701712299442, "uuid": "ea118b00-f824-4d36-ad7b-f7ae4524f1f5", "historyId": "127c61d8a174f7d1b3d13f4126215f84", "testCaseId": "3ede36b7589fd4aecb657c5bdf84cfe1", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_missing_field_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_new_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-O6MNHQN"}, {"name": "thread", "value": "9112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}